// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbwlmsskwqglpdrbfvwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1id2xtc3Nrd3FnbHBkcmJmdndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDMwODQsImV4cCI6MjA3NDQ3OTA4NH0.wdBtu4hgxLluHu0K4JKxDN1DvLMeWv9vOUh9akwpjeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});